{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "backintimechart.labels" . | nindent 4 }}
  name: leader-locking-{{ template "backintimechart.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "backintimechart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leader-locking-{{ template "backintimechart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
