apiVersion: v1
kind: Service
metadata:
  name: backintime
spec:
  selector:
    app: backintime
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 22

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backintime
  labels:
    app: backintime
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backintime
  template:
    metadata:
      labels:
        app: backintime
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"172.16.0.1\"]"
    spec:
      serviceAccountName: python-client
      containers:
        - name: backintime
          image: imenhr/ssh-repo:v4
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true 
            capabilities: 
               add:  
                  - SYS_ADMIN
          ports:
            - name: ssh
              containerPort: 22
